version: '3'

services:

    app:
      build: .
      container_name: apresentacao
      entrypoint: ./.docker/app/entrypoint.sh
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=apresentacao
        - DB_USERNAME=root
        - DB_PASSWORD=root
        - APP_HOST=app
        - PORT_HOST=9000
      volumes:
        - .:/var/www
      depends_on:
          - db
      networks:
        - app-network

    nginx:
      build: .docker/nginx
      container_name: nginx
      restart: always
      tty: true
      depends_on:
          - app
      ports:
        - "8088:80"
      volumes:
        - .:/var/www
      networks:
        - app-network

    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      ports:
          - "33006:3306"
      volumes:
          - ./.docker/db/data:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=root
          - MYSQL_DATABASE=apresentacao
      networks:
          - app-network


networks:
  app-network:
      driver: bridge